VIC-4311 Filters added to EventStream (#3075)
Also added KeepAlive ping to the EventStream to make sure it stays alive while connected

diff --git a/tools/sdk/grpc_tools/Makefile b/tools/sdk/grpc_tools/Makefile
--- a/tools/sdk/grpc_tools/Makefile
+++ b/tools/sdk/grpc_tools/Makefile
@@ -104,6 +104,21 @@ create_certs: .require_ip
 	chmod 660 trust.cert
 certs: create_certs
 
+download_cert:
+ifeq ("$(ANKI_ROBOT_SERIAL)","")
+	$(error Could not find ANKI_ROBOT_SERIAL environment variable)
+endif
+	curl https://session-certs.token.global.anki-services.com/vic/$(ANKI_ROBOT_SERIAL) > trust.cert
+	@if grep -xq "\-----BEGIN CERTIFICATE-----" trust.cert; \
+	then \
+		echo "Download successful!"; \
+	else \
+		echo "Download failed!\n"; \
+		cat trust.cert ; \
+		echo "\n\nVerify that your robot has been logged in properly, and the certificate is in the cloud"; \
+		exit 1; \
+	fi
+
 create_certs_mac: .PHONY
 	cp trust.conf temp_trust.conf
 	echo "DNS.1 = $(MAC_VECTOR_HOSTNAME)" >> temp_trust.conf
@@ -121,6 +136,14 @@ example_curl: .require_ip
 
 test_curl_events: .require_ip
 	$(curl_command)/v1/event_stream -d '{}'
+	@echo
+
+test_curl_events_white: .require_ip
+	$(curl_command)/v1/event_stream -d '{"white_list": {"list": ["wake_word"]}}'
+	@echo
+
+test_curl_events_black: .require_ip
+	$(curl_command)/v1/event_stream -d '{"black_list": {"list": ["robot_state", "robot_observed_face"]}}'
 	@echo
 
 test_get_events: .require_ip
