allocte error code block for headprogram script exit codes

diff --git a/robot/fixture/tools/release/headprogram b/robot/fixture/tools/release/headprogram
--- a/robot/fixture/tools/release/headprogram
+++ b/robot/fixture/tools/release/headprogram
@@ -3,6 +3,12 @@ ESN=$1
 HW_VER=0001
 MODEL=0001
 
+#exit code RESERVED RANGE: 960-970
+ERROR_HEADPGM_OUT_OF_CLOUD_CERTS=960
+ERROR_HEADPGM_MISSING_CERT=961
+ERROR_HEADPGM_BAD_CERT=962
+#963-969 RFU
+
 helper=0
 for arg in "$@"; do
   #echo arg: \""${arg}"\" #DEBUG
@@ -37,10 +43,10 @@ mkdir /data/img/cloud                                   || exit 103
 # Prepare cloud data for this ESN
 if [ $helper -eq 0 ]; then
   echo unpacking cert...
-  unzip -d /data/img/cloud /anki/certs.zip $ESN/*         || exit 105
+  unzip -d /data/img/cloud /anki/certs.zip $ESN/*         || exit $ERROR_HEADPGM_BAD_CERT
   if [ ! -e /data/img/cloud/$ESN ]; then
     echo no cert found for ESN $ESN
-    exit 105
+    exit $ERROR_HEADPGM_MISSING_CERT #ERROR_HEADPGM_OUT_OF_CLOUD_CERTS
   fi
   mv /data/img/cloud/$ESN/* /data/img/cloud               || exit 105
   chmod 0440 /data/img/cloud /data/img/cloud/*            || exit 105
