improve headprogram arg parsing & error code handling

diff --git a/robot/fixture/tools/release/headprogram b/robot/fixture/tools/release/headprogram
--- a/robot/fixture/tools/release/headprogram
+++ b/robot/fixture/tools/release/headprogram
@@ -2,16 +2,18 @@
 ESN=$(echo $1 | xargs)
 HW_VER=0001
 MODEL=0001
+echo headprogram esn $ESN hwvers $((HW_VER)) model $((MODEL))
 
-#exit code RESERVED RANGE: 960-970
-ERROR_HEADPGM_OUT_OF_CLOUD_CERTS=960
-ERROR_HEADPGM_MISSING_CERT=961
-ERROR_HEADPGM_BAD_CERT=962
-#963-969 RFU
+#exit codes RESERVED RANGE: 960-970
+ERROR_OFFSET=$((960-60)) #shift error codes to start from 60 (valid exit range 0-255)
+ERROR_HEADPGM_MISSING_CERT=$((960-$ERROR_OFFSET))
+ERROR_HEADPGM_BAD_CERT=$((961-$ERROR_OFFSET))
+ERROR_HEADPGM_FAC_IMG=$((962-$ERROR_OFFSET))
 
 helper=0
 for arg in "$@"; do
-  echo arg: \""${arg}"\" #DEBUG
+  #argCnt=$((argCnt+1))
+  #echo arg[$argCnt] raw:\""${arg}"\" trimmed:\""$(echo ${arg} | xargs)"\"
   if [ "$(echo ${arg} | xargs)" == "helper" ]; then echo "making helper head"; helper=1; ESN=0; fi
 done
 
@@ -25,34 +27,38 @@ if [ "$mode" != "host" ]; then
   echo 1094400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
   insmod ./usbserial.ko vendor=0x05c6 product=0x9008
 fi
+
 # Reboot if USB did not switch the first time - only a reboot can fix it
 mode=$(cat /sys/kernel/debug/msm_otg/mode)
 if [ "$mode" != "host" ]; then
   reboot
 fi
+
 # Prepare factory partition image
 umount /data/img
 rm emmcdl/factory.img
 mkdir -p /data/img
-dd if=/dev/zero of=emmcdl/factory.img count=4 bs=1M     || exit 101
-yes | mkfs.ext4 emmcdl/factory.img                      || exit 102
-mount -o loop emmcdl/factory.img /data/img              || exit 103
-mkdir /data/img/cloud                                   || exit 103
+dd if=/dev/zero of=emmcdl/factory.img count=4 bs=1M       || exit $ERROR_HEADPGM_FAC_IMG
+yes | mkfs.ext4 emmcdl/factory.img                        || exit $ERROR_HEADPGM_FAC_IMG
+mount -o loop emmcdl/factory.img /data/img                || exit $ERROR_HEADPGM_FAC_IMG
+mkdir /data/img/cloud                                     || exit $ERROR_HEADPGM_FAC_IMG
 # Set up birth certificate on factory partition
-./makebc /data/img/birthcertificate $ESN $HW_VER $MODEL || exit 104
+./makebc /data/img/birthcertificate $ESN $HW_VER $MODEL   || exit $ERROR_HEADPGM_FAC_IMG
+
 # Prepare cloud data for this ESN
 if [ $helper -eq 0 ]; then
   echo unpacking cert...
   unzip -d /data/img/cloud /anki/certs.zip $ESN/*         || exit $ERROR_HEADPGM_BAD_CERT
   if [ ! -e /data/img/cloud/$ESN ]; then
-    echo no cert found for ESN $ESN
-    exit $((ERROR_HEADPGM_MISSING_CERT)) #ERROR_HEADPGM_OUT_OF_CLOUD_CERTS
+    echo no cert found for ESN $ESN;                         exit $ERROR_HEADPGM_MISSING_CERT
   fi
-  mv /data/img/cloud/$ESN/* /data/img/cloud               || exit 105
-  chmod 0440 /data/img/cloud /data/img/cloud/*            || exit 105
-  chown 888:888 /data/img/cloud /data/img/cloud/*         || exit 105
+  mv /data/img/cloud/$ESN/* /data/img/cloud               || exit $ERROR_HEADPGM_FAC_IMG
+  chmod 0440 /data/img/cloud /data/img/cloud/*            || exit $ERROR_HEADPGM_FAC_IMG
+  chown 888:888 /data/img/cloud /data/img/cloud/*         || exit $ERROR_HEADPGM_FAC_IMG
 fi
-umount /data/img                                        || exit 106
+umount /data/img                                        || exit $ERROR_HEADPGM_FAC_IMG
+
 # Flash the robot
 lsusb
 ./emmcdl/emmcdl -p 0 -f emmcdl/prog_emmc_firehose_8909_ddr.mbn -x emmcdl/anki.xml -SetActivePartition 0
+
